// Stub — Sidebar components unused in this app.
const _noop = () => null;
export const Sidebar = _noop;
export const SidebarContent = _noop;
export const SidebarFooter = _noop;
export const SidebarGroup = _noop;
export const SidebarGroupAction = _noop;
export const SidebarGroupContent = _noop;
export const SidebarGroupLabel = _noop;
export const SidebarHeader = _noop;
export const SidebarInput = _noop;
export const SidebarInset = _noop;
export const SidebarMenu = _noop;
export const SidebarMenuAction = _noop;
export const SidebarMenuBadge = _noop;
export const SidebarMenuButton = _noop;
export const SidebarMenuItem = _noop;
export const SidebarMenuSkeleton = _noop;
export const SidebarMenuSub = _noop;
export const SidebarMenuSubButton = _noop;
export const SidebarMenuSubItem = _noop;
export const SidebarProvider = _noop;
export const SidebarRail = _noop;
export const SidebarSeparator = _noop;
export const SidebarTrigger = _noop;
export const useSidebar = () => ({});
